import { ThemeProvider } from "@/components/theme";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, SignedIn, currentUser } from "@clerk/nextjs";
import prisma from "@/lib/prisma";
import Sidebar from "@/components/sidebar";

const satoshi = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
  display: "swap",
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  if (user) {
    // check if the user exists in the database
    const dbUser = await prisma.user.findUnique({
      where: {
        id: user.id,
      },
    });

    if (!dbUser) {
      await prisma.user.create({
        data: {
          id: user.id,
          email: user.emailAddresses[0].emailAddress,
          name:
            (user.firstName ? user.firstName + " " : "") +
            (user.lastName ?? ""),
        },
      });
    }
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={satoshi.className}>
          <ThemeProvider attribute="class" defaultTheme="light">
            <main className="flex h-screen w-screen items-start justify-start overflow-hidden">
              <SignedIn>
                <Sidebar />
              </SignedIn>
              <div className="flex w-full flex-col items-center  px-4 py-8 lg:px-8 xl:px-16">
                {children}
              </div>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
