import { ThemeProvider } from "@/components/theme";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, SignedIn, currentUser } from "@clerk/nextjs";
import prisma from "@/lib/prisma";
import Sidebar from "@/components/sidebar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { TanStackQueryProvider } from "@/lib/tanstackQueryProvider";

const satoshi = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
  display: "swap",
  variable: "--font-satoshi",
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  if (user) {
    // check if the user exists in the database
    const dbUser = await prisma.user.findUnique({
      where: {
        id: user.id,
      },
    });

    if (!dbUser) {
      await prisma.user.create({
        data: {
          id: user.id,
          email: user.emailAddresses[0].emailAddress,
          name:
            (user.firstName ? user.firstName + " " : "") +
            (user.lastName ?? ""),
        },
      });
    }
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={satoshi.className}>
          <TanStackQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="light">
              <main className="flex h-screen w-screen items-start justify-start overflow-hidden">
                <SignedIn>
                  <Sidebar />
                </SignedIn>
                {children}
              </main>
            </ThemeProvider>
          </TanStackQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
